config/routes.rb
Rails.application.routes.draw do
 
  
  root to: 'home#index'
  devise_for :users
  resources :order, only: [:new, :create]
  resources :cart, only: [:show, :update, :destroy, :edit]
  resources :bills, only: [:destroy, :create]




  scope '/checkout' do
	post 'create', to: 'checkout#create', as: 'checkout_create'
	get 'success', to: 'checkout#success', as: 'checkout_success'
	get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end



  resources :item, only: [:show, :update, :destroy, :edit] do
    resources :picture, only: [:create]
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

    after_create :order_confirmation

    
    def admin_confirmation
      OrderMailer.admin_confirmation(self).deliver_now
    end
      
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :bills
  has_many :items, through: :bills
end

app/models/flow.rb
class Flow < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/models/item.rb
class Item < ApplicationRecord

  validates :title, :description, :price, :image_url, presence: true
  validates :title, length: { in: 3..100 }
  validates :description, length: { in: 5..500 }
  validates :price, numericality: { greater_than: 0.0 }

  has_many :bills
  has_many :carts, through: :bills

  has_many :flows
  has_many :orders, through: :flows
  has_one_attached :picture
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :flows
  has_many :items, through: :flows

  after_create:order_confirmation_send

  def order_confirmation_send
    OrderMailer.order_confirmation(self).deliver_now
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


    after_create :welcome_send, :create_cart
	
  has_one :cart
  has_many :orders

	def welcome_send
		UserMailer.welcome(self).deliver_now
	end 

  def create_cart
    Cart.create(user_id: self.id)
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def create
    @bill = Bill.new(cart_id: current_user.cart.id, item_id: params[:item_id])

    if @bill.save == true
      respond_to do |format|
        format.html {redirect_to root_path, :succes => "Ajouté au panier !"}
        format.js { }
      end
    else
      redirect_to root_path, :warning => "Erreur !"
    end
  end

  def destroy
    @bill = Bill.where(cart_id: current_user.cart.id, item_id: params[:id])
    @stock = params[:id]
    @bill.destroy_all
    @total = sum(current_user)

    respond_to do |format|
      format.html { redirect_to cart_path(current_user.cart.id) }
      format.js {}
    end
  end

  private

  def sum (user)
    result = 0
    user.cart.items.each do |item|
      result = result + item.price
    end
    return result
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = Cart.find(params[:id])
    @item = Item.find(params[:id])
    # @user = User.find
  end

  def update
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart = Cart.find(params[:id])
    @order = Order.create(user_id: current_user.id)
    @cart.items.each do |item|
      Flow.create(order_id: @order.id, item_id: item.id)
    end

    @cart.items.destroy_all
    redirect_to root_path, :info => "Merci pour votre commande, vous allez bientôt recevoir un email !"

  end
  
  private

  def authenticate_user
    unless user_signed_in?
      flash[:danger] = "Please log in."
      redirect_to root_path
    end
  end


end




# <%= button_to "Supprimer l'article", cart_path(current_user.id), :item_id => item.id, :method => "post" %>   

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

  # after_action :delete, only: :success

	def create
    @total = params[:total].to_d
    puts @total
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          name: 'Rails Stripe Checkout',
          amount: (@total*100).to_i,
          currency: 'eur',
          quantity: 1
        },
      ],
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    puts @session
    respond_to do |format|
      format.js {}# renders create.js.erb
    end
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)


    @cart = Cart.find_by(user_id: current_user.id)
    @order = Order.create(user_id: current_user.id)
    @cart.items.each do |item|
      Flow.create(order_id: @order.id, item_id: item.id)
    end

    @cart.items.destroy_all
    redirect_to root_path, :info => "Merci pour votre commande, vous allez bientôt recevoir un email !"

  end

  def cancel
  end

# private
#   def delete
#      redirect_to: cart_path(@cart.id), :method =>:delete 
#   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@item = Item.all
  end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
    def show
        @item = Item.find(params[:id])
     end
    
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
    def create
    end
end

app/controllers/picture_controller.rb
class PictureController < ApplicationController
	def create
		@item = Item.find(params[:item_id])
		@item.picture.attach(params[:picture])
		redirect_to(item_path(@item))
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end
end

app/helpers/bill_helper.rb
module BillHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/views/bills/_add_cart.html.erb
<% if current_user.cart.items.count > 0 %>
  <%= link_to "PANIER (#{current_user.cart.items.count})", cart_path(current_user.cart.id),id:"panier_nav", class:"links" %>
<% else %>  
  <%= link_to "PANIER", cart_path(current_user.cart.id),id:"panier_nav", class:"links" %>
<% end %>

app/views/bills/_total-price.html.erb
<p id="total-price">total : <%= total %>€</p> 

app/views/bills/create.js.erb
document.getElementById("nav").removeChild(document.getElementById("panier_nav"));
document.getElementById("delog").insertAdjacentHTML("beforebegin", "<%= j render 'add_cart' %>");
alert("Ajouté au panier");

app/views/bills/destroy.js.erb
document.getElementById("item<%= @stock %>").remove();
document.getElementById("button<%= @stock %>").remove();
document.getElementById("total").removeChild(document.getElementById("total-price"));
document.getElementById("total").insertAdjacentHTML("beforeend", "<%= j render 'total-price', total:@total %>");
document.getElementById("nav").removeChild(document.getElementById("panier_nav"));
document.getElementById("delog").insertAdjacentHTML("beforebegin", "<%= j render 'add_cart' %>");

app/views/cart/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>cart</title>
</head>
<body>

	<div id="pageCart">
			<div id="cart">
				<p id="row1">
					<%= @user %>
				</p>
					<% total = 0 %>
				<% @cart.items.each do |item| %>
					<p class="each" id="item<%= item.id %>">
						<%if item.picture.attached?%>
							<%= image_tag item.picture, alt: 'avatar', class:"icon" %>
							<% puts "salut" %>
						<% else %>
								<img class="icon" src="<%= item.image_url %>">
								<% puts"bonjour " +  "#{item.id}" %>
						<%end%>
						<%= item.title %>
						<span><%= item.price %>€</span>
						<%= button_to "Supprimer l'article", bill_path(item.id), :method =>:delete, id: "button#{item.id}", remote: true, class:"deux" %>
					</p>
						<% total = total + item.price %>
				<% end %>
						

					


					
			</div>
			<div id="total">
							<p id="total-price">total : <%= total %>€</p>	
						</div>
					<% if total >= 1 %>
						<%= button_to "Passer commande", checkout_create_path(total: total), remote: true, class:"un"  %>
					<% end %>
	</div>

</body>
</html>

app/views/item/show.html.erb
<div class="quatre">

	<%if @item.picture.attached?%>
		<%= image_tag @item.picture, alt: 'avatar' %>
	<% else %>
		<img src="<%= @item.image_url %>">
	<%end%>

  <p><h2><%= @item.title%></h2></p>
  <p><h3><%= @item.description%></h3></p>
<%= button_to "Ajouter au panier", bills_path, action: "create" ,method: :post,remote: true, params: {item_id: @item.id}, class:"ca btn btn-success" %>
</div>